### ISSUE TITLE
Login with Google failed on Emulator Pixel 3 (API 24)

### ISSUE THREAD

**Issue by quocnd** [torusresearch/torus-direct-android-sdk#18]
## Conditions
- Emulator Pixel 3 (API 24)
- Or some emulators/phones with API < API 26
## Steps
1. Select `Google` for social platform
2. Click `Launch`
3. Wait a bit
4. Click `click here`
5. Observe result => Error message

## Screenshots
![torus_launch_failed](https://user-images.githubusercontent.com/10803943/160802595-fd0edb84-b4bd-456d-9957-e6f401896321.gif)

## Logs
`2022-03-30 16:30:40.821 3549-5778/org.torusresearch.customauth.app E/result:error: error
    java8.util.concurrent.CompletionException: java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
        at java8.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:336)
        at java8.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:352)
        at java8.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
        at java8.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:523)
        at java8.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2170)
        at org.web3j.utils.Async.lambda$run$1(Async.java:40)
        at org.web3j.utils.Async$$ExternalSyntheticLambda1.run(Unknown Source)
        at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1813)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar)
        at org.web3j.abi.TypeReference.getClassType(TypeReference.java:94)
        at org.web3j.abi.DefaultFunctionReturnDecoder.getDataOffset(DefaultFunctionReturnDecoder.java:159)
        at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:86)
        at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:52)
        at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:49)
        at org.web3j.tx.Contract.executeCall(Contract.java:295)
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:301)
        at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:312)
        at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1$org-web3j-tx-Contract(Contract.java:400)
        at org.web3j.tx.Contract$$ExternalSyntheticLambda14.call(Unknown Source)
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
        at org.web3j.protocol.core.RemoteCall$$ExternalSyntheticLambda0.call(Unknown Source)
        at org.web3j.utils.Async.lambda$run$1(Async.java:38)
        at org.web3j.utils.Async$$ExternalSyntheticLambda1.run(Unknown Source) 
        at java8.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1813) `

**Comment by quocnd** [comment]
Does anyone in the team take a look on this issue?

**Comment by grvgoel81** [comment]
Its fixed now. Please try latest version.
